---

- hosts: all        # Run in all Hosts on inventary
  become: true      # Run with sudo privileges
  tasks:            # The tasks to run 

# UBUNTU DISTRO
  - name: Update Repository Index        # Simple indicative name
    apt:                                 # Module apt
      update_cache: yes                  # update index Cache
    when: ansible_distribution == 'Ubuntu'

  - name: install apache2 package        # Indicative Name
    apt:                                 # Module APT
      name: apache2                      # The package
      state: latest                      # Latest version
    when: ansible_distribution == 'Ubuntu'

  - name: add php Support for Apache     # Simple indicative name
    apt:                                 # Module apt
      name: libapache2-mod-php5          # The package
      state: latest                      # Latest version
    when: ansible_distribution == 'Ubuntu'

# CENTOS DISTRO
  - name: Update Repository Index        # Simple indicative name
    dnf:                                 # Module apt
      update_cache: yes                  # update index Cache
    when: ansible_distribution == 'CentOS'

  - name: install apache2 package        # Indicative Name
    dnf:                                 # Module APT
      name: httpd.x86_64                      # The package
      state: latest                      # Latest version
    when: ansible_distribution == 'CentOS'

  - name: add php Support for Apache     # Simple indicative name
    dnf:                                 # Module apt
      name: php.x86_64          # The package
      state: latest                      # Latest version
    when: ansible_distribution == 'CentOS'