---

- hosts: all        # Run in all Hosts on inventary
  become: true      # Run with sudo privileges
  tasks:            # The tasks to run 

  - name: update and install apache2, php package for Ubuntu      # Indicative Name
    apt:                                 # Module APT
      name:         
        - apache2   
        - libapache2-mod-php5         # The package
      state: absent  
      update_cache: yes                     # Latest version
    when: ansible_distribution == 'Ubuntu'  # Remove the package
# CENTOS DISTRO

  - name: update and install httpd, php package for CentOS        # Indicative Name
    dnf:                                 # Module APT
      name:
        - httpd
        - php                     # The package
      state: absent 
      update_cache: yes                       # Latest version
    when: ansible_distribution == 'CentOS'