---

- hosts: all        # Run in all Hosts on inventary
  become: true      # Run with sudo privileges
  pre_tasks:            # The tasks to run 

# Centos
  - name: Install Updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

# Ubuntu
  - name: Install Update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

# Install WebServers packages

  - name: update and install apache2, php package for Ubuntu      # Indicative Name
    apt:                                 # Module APT
      name:
        - apache2   
        - libapache2-mod-php5         # The package
      state: latest  
    when: ansible_distribution == 'Ubuntu'

  - name: update and install httpd, php package for CentOS        # Indicative Name
    dnf:                                 # Module APT
      name:
        - httpd
        - php                     # The package
      state: latest 
    when: ansible_distribution == 'CentOS'

# Install MariaDB packages

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariDB package
    dnf: 
      name: mariadb-server
      state: latest
    when: ansible_distribution ==  'CentOS'

  - name: Install MariDB package
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution ==  'Ubuntu'

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    package: 
      name: samba
      state: latest