- name: update and install apache2, php package for Ubuntu      # Indicative Name
  tags: apache,httpd,php
  package:                                 # Module APT
    name:
      - "{{ apache_package_name }}" 
      - "{{ php_package_name }}"         # The package
    state: latest

- name: Start httpd (CENTOS)
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Change Email Addres for admin
  tags: apache, centos, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin test@gmail.c.net'
  when: ansible_distribution == 'CentOS'
  notify: restart_apache     # Simple add an Handler

- name: Copy Default html file for site
  tags: httpd, centos, apache
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644