Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.define "node-#{i}" do |node|
	    node.vm.box = "ubuntu/trusty64"
      #node.vm.network "private_network", ip: "192.168.1.#{i}"
      node.vm.network "public_network", ip: "192.168.1.12#{i}"
	    node.vm.provision "shell", inline: "echo hello from node #{i}"
    end
  end
end